### ISSUE TITLE
Snap/deb package

### ISSUE THREAD

**Issue by pharaone** [AlanGriffiths/egmde#1]
Why don't you try offering egmde as a .deb or snap package?(I had problems compiling it, so i'm asking for a package, i'm a noob at compiling :D)

**Comment by AlanGriffiths** [comment]
Did you eventually succeeded in compiling it? What guidance would have helped? 
The point of an example is to help, not to replace, a developer using MirAL, your experience can be part of this.

**Comment by pharaone** [comment]
that's the problem I had, how can I solve it?
![cattura6](https://user-images.githubusercontent.com/17162630/38170395-f8fbc2c2-3584-11e8-91ec-5512d13546de.PNG)

**Comment by AlanGriffiths** [comment]
That's cmake's way of saying it can't find a compiler. Let's add one:

    $ sudo apt install g++

**Comment by pharaone** [comment]
thanks, I did everything but now it is stuck here (after switching to vt4 and writing "./egmde-desktop")
![catturrea](https://user-images.githubusercontent.com/17162630/38171870-ff30a05a-35a1-11e8-9e9d-6ac6033b51ae.PNG)

**Comment by AlanGriffiths** [comment]
First: Press Ctrl-C to stop that. Something went wrong launching the server.
 
There will be an error message before that. But it's a good guess that what is missing is the Mir graphics drivers for your system:

    $ sudo apt install mir-graphics-drivers-desktop

Also, you will likely find it more convenient if you switch back to VT2 before typing `./egmde-desktop`.

Thanks for this feedback, I'll update the article to cover this.

**Comment by pharaone** [comment]
Thanks! Now it works ! Looks like I found a bug
![cattura22](https://user-images.githubusercontent.com/17162630/38172025-14204468-35a5-11e8-8dea-bd5fc7763d68.PNG)
if you make the screen bigger after you launched egmde, the wallpaper will stay small as the screen was before. Thanks for before!!

**Comment by AlanGriffiths** [comment]
Great!
I'll close *this* issue. (The screen resizing issue deserves one of its own.)
