### ISSUE TITLE
Egmde doesn't start on real hardware

### ISSUE THREAD

**Issue by pharaone** [AlanGriffiths/egmde#11]
I tried to run egmde on my pc but it doesn't work(mir problem?)
Acer aspire one d255, Intel atom n450
![0c88063b-e082-437c-980d-ef823ab13b57](https://user-images.githubusercontent.com/17162630/39423156-f20b5768-4c70-11e8-82b5-4a0df43e8037.jpeg)

**Comment by AlanGriffiths** [comment]
I don't see the command you entered.

Could you confirm that you followed [the article:](https://community.ubuntu.com/t/egmde-keymap-and-wallpaper/5164)

After this you can start a basic egmde based desktop. This will use VT4, so first switch to VT4 (Ctrl-Alt-F4) to sign in and switch back again. Then type:
```
$ ./egmde-desktop
```
You should see a simple gradient wallpaper with a weston-terminal session.

**Comment by pharaone** [comment]
Yes, I did everything

Il lun 30 apr 2018, 12:29 Alan Griffiths <notifications@github.com> ha
scritto:

**Comment by AlanGriffiths** [comment]
Please paste (or pastebin) the full error text. I can't see enough in the image to identify the problem.

**Comment by pharaone** [comment]
Here it is: https://pastebin.com/S6M7X3qP

>

**Comment by AlanGriffiths** [comment]
Ah. You have a mix of release and development builds of Mir installed, that's not normally a problem but I guess you've hit one of those cases where development.

You probably have ppa:mir-team/release as well as /dev in which case:

$ sudo ppa-purge mir-team/release

Will resolve the conflict.

**Comment by AlanGriffiths** [comment]
:(

Can you paste the output from this?
`
$ apt show -a mir-graphics-drivers-desktop
`

**Comment by AlanGriffiths** [comment]
Nothing wrong there, and no obvious clues in the log.

Things to try:

1. `$ miral-desktop` (you need to install mir-demos) I expect it to fail the same way, but if it doesn't that's interesting.
2. `$ ./egmde-app` that should run in a window on your desktop. It will be interesting to know if that works.
3. rebuilding egmde: `$ make clean all` (a long shot, but just might fix things)

**Comment by pharaone** [comment]
Nothing worked, here there is what miral shows :
https://pastebin.com/pM22bvX2
Very similar to egmde

Il lun 30 apr 2018, 14:38 Alan Griffiths <notifications@github.com> ha
scritto:

**Comment by pharaone** [comment]
Just tried with recovery mode and everything worked, so I tried to repair damaged packages from recovery and now egmde works normally. 
Thanks anyway
