### ISSUE TITLE
Window resizing isn't smooth

### ISSUE THREAD

**Issue by punhetonildo** [AlanGriffiths/egmde#13]
It stutters, very different from the unity 8 desktop which is smooth.

**Comment by AlanGriffiths** [comment]
I suspect this is an issue with the Mir Wayland support, and probably one that already has a fix. 

Which version of Mir are you using?

While both Unity8 and egmde use Mir they currently do so very differently, Unity8 largely uses the mirclient support.

**Comment by punhetonildo** [comment]
I'm using the latest version available in the mir team ppa (dev), also the egmde is the latest (edge). 
I should note that my hardware is a low end notebook with a core i3.

**Comment by punhetonildo** [comment]
ops

**Comment by punhetonildo** [comment]
I can record a video but i don't know how to do that in mir.

**Comment by AlanGriffiths** [comment]
> I can record a video but i don't know how to do that in mir.

There's a script - miral-screencast in mir-demos that demonstrates how. But you don't need to, you're right, this is much more obvious on a slower device, but I can see confirm it.

(Closing this issue to track as a Mir bug: https://github.com/MirServer/mir/issues/604)
