### ISSUE TITLE
Fails to start if ~/.config does not exist

### ISSUE THREAD

**Issue by wmww** [AlanGriffiths/egmde#29]
I've only observed this using the snap in Raspbian on a Pi, so the bug could be specific to one of those things. On a fresh install there is no `/home/pi/.config` directory. egmde fails fails with
```
/snap/egmde/2427/bin/egmde.launcher: line 27: /home/pi/.config/egmde.config: No such file or directory
```
`mkdir ~/.config` appears to fix the problem. No reinstallation, reboot or anything required.

NOTE: I'm aware the snap probably wont actually work on the Pi

**Comment by AlanGriffiths** [comment]
This is an issue with the Mir library, raised there.
