### ISSUE TITLE
If closing Xwayland, egmde crashes

### ISSUE THREAD

**Issue by pharaone** [AlanGriffiths/egmde#5]
I don't know if that's a bug, but if you close ibus-x11 and after that you close xwayland , egmde crashes.
![d](https://user-images.githubusercontent.com/17162630/38173797-12f041aa-35c4-11e8-9fd8-40708eeca6a5.gif)

**Comment by AlanGriffiths** [comment]
Killing arbitrary processes is bad idea. I don't think egmde is using these, but your gnome session probably is.

**Comment by pharaone** [comment]
so my gnome-session is still running somewhere?

**Comment by AlanGriffiths** [comment]
Yes, on VT2

**Comment by pharaone** [comment]
Ah ok, thanks for the infos!

Il dom 1 apr 2018, 17:12 Alan Griffiths <notifications@github.com> ha
scritto:

**Comment by AlanGriffiths** [comment]
Yes, this is not an egmde issue.
