### ISSUE TITLE
session not established on Ubuntu Budgie 21.04

### ISSUE THREAD

**Issue by fossfreedom** [AlanGriffiths/egmde#55]
snap install egmde --edge --classic

I thought I try this on top of Ubuntu Budgie 21.04 - after a reboot I see egmde in lightdm-slick greeter but the session isnt started and returns back to the greeter.  Is there any instructions what to look for in journalctl (?) / anything else to diagnose why the session doesnt start?

**Comment by AlanGriffiths** [comment]
Hi, @fossfreedom 

I have seen issues raised with lightdm, but haven't tested recently. Here's the earlier report (based on testing with 16.04):

https://github.com/MirServer/egmde-snap/issues/2

To experiment, you can likely bypass this by logging into a VT and running:
```
egmde --shell-enable-autostart
```
That logs to the console, so if it fails you can preserve the logs with:
```
egmde --shell-enable-autostart &> egmde.log
```
HTH

**Comment by fossfreedom** [comment]
Thanks!

via VT `egmde --shell-enable-autostart` launches egmde successfully

**Comment by fossfreedom** [comment]
[lightdm.log](https://github.com/AlanGriffiths/egmde/files/6284214/lightdm.log)
[seat0-greeter.log](https://github.com/AlanGriffiths/egmde/files/6284216/seat0-greeter.log)

**Comment by AlanGriffiths** [comment]
```plain
[+13.68s] DEBUG: Session pid=2526: Running command /usr/sbin/lightdm-session sh -l -c 'exec egmde --shell-enable-autostart'
[+13.68s] DEBUG: Creating shared data directory /var/lib/lightdm-data/dad
[+13.68s] DEBUG: Session pid=2526: Logging to .xsession-errors
[+13.93s] DEBUG: Activating VT 8
[+14.43s] DEBUG: Seat seat0: Stopping greeter
[+14.43s] DEBUG: Terminating login1 session c1
[+14.44s] DEBUG: Session pid=2066: Sending SIGTERM
[+14.44s] DEBUG: Activating login1 session c2
```
Maybe something from `Logging to .xsession-errors`?

**Comment by fossfreedom** [comment]
lol - yeah - well that uncovered an issue with two Ubuntu Budgie /etc/profile.d/ scripts (bashism vs bourne at a guess).  Anyway - moving those two profile scripts aside (10-budgie-desktop.sh and 10-budgie-desktop-common.sh) shows the following in the .xsession-errors log

[xsession-errors.log](https://github.com/AlanGriffiths/egmde/files/6284308/xsession-errors.log)

**Comment by AlanGriffiths** [comment]
Not sure where it originates, but `egmde: 1: Syntax error: Unterminated quoted string` looks like it is the immediate problem.

Perhaps something is mangling the Exec command from `/usr/share/wayland-sessions/egmde`? Vis:

```plain
[Desktop Entry]
Name=egmde
Comment=The example Mir server
Exec=sh -l -c 'exec egmde --shell-enable-autostart'
Type=Application
```

**Comment by AlanGriffiths** [comment]
@fossfreedom did you get anywhere with this?

**Comment by AlanGriffiths** [comment]
It would be interesting to see if the quotes in the `Exec` line are the problem. That works with GDM and SSDM, but the above error message makes me wonder if lightdm does something differently.

I've created a test snap (based on https://github.com/MirServer/egmde-snap/pull/52) that you could try with:
```
snap install --classic --channel edge/pr52 egmde
```
This also forces egmde to log to `~/egmde.log`, so if it does fail there's an easy place find errors.

**Comment by fossfreedom** [comment]
Thx.

Well how odd.

I removed the edge egmde and installed edge/pr52 and rebooted.

I can now successfully log in - the panel options could be clicked.  I didnt see the overlay showing the keyboard options.  But at least a hippo backdrop and panel were visible.

I then removed this new version of egmde and went back to the edge version of channel (reinstalled).  Rebooted and confirmed that I couldnt log into the session.

[egmde.log](https://github.com/AlanGriffiths/egmde/files/6301851/egmde.log)

**Comment by AlanGriffiths** [comment]
> I can now successfully log in

That's good news! I'll update edge based on that feedback.

> I didnt see the overlay showing the keyboard options.

That's expected. The swaybg background replaces that. (That's the thing with edge, stuff isn't always "done done".)
